name: Deploy Frontend
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      - run: docker build -t fatihidris/docker-react -f Dockerfile.dev .
      - run: docker run -e CI=true fatihidris/docker-react npm test

      - name: Generate deployment package
        run: zip -r deploy.zip . -x '*.git*'

      - name: Deploy to Elastic Beanstalk
        uses: einaregilsson/beanstalk-deploy@v21
        with:
          application_name: frontend
          environment_name: Frontend-env
          version_label: ${{ github.sha }}
          region: ap-southeast-2
          existing_bucket_name: elasticbeanstalk-ap-southeast-2-266097584661
          deployment_package: deploy.zip
          use_existing_version_if_available: true          
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
